import type { FlatToken, GeneratorFn } from "../types";

function groupByFirstSegment(tokens: FlatToken[]): Map<string, FlatToken[]> {
  const groups = new Map<string, FlatToken[]>();
  for (const token of tokens) {
    const group = token.path[0] ?? "other";
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group)!.push(token);
  }
  return groups;
}

export const generateCSS: GeneratorFn = (tokens) => {
  const lines: string[] = [
    "/* Generated by design-token-pipeline — do not edit */",
    "",
    ":root {",
  ];

  const groups = groupByFirstSegment(tokens);
  let first = true;

  for (const [group, groupTokens] of groups) {
    if (!first) lines.push("");
    first = false;
    lines.push(`  /* ${group} */`);
    for (const token of groupTokens) {
      lines.push(`  --${token.name}: ${token.value};`);
    }
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};
