import type { FlatToken, GeneratorFn } from "../types";

const TAILWIND_NAMESPACE_MAP: Record<string, string> = {
  radii: "radius",
};

const TAILWIND_PATH_MAP: Record<string, string> = {
  "font-lineHeight": "line-height",
  "font-size": "font-size",
  "font-family": "font-family",
  "font-weight": "font-weight",
};

function toTailwindName(token: FlatToken): string {
  const firstSegment = token.path[0];

  if (firstSegment && TAILWIND_NAMESPACE_MAP[firstSegment]) {
    const rest = token.path.slice(1).join("-");
    return `${TAILWIND_NAMESPACE_MAP[firstSegment]}${rest ? `-${rest}` : ""}`;
  }

  const twoSegment = token.path.slice(0, 2).join("-");
  if (TAILWIND_PATH_MAP[twoSegment]) {
    const rest = token.path.slice(2).join("-");
    return `${TAILWIND_PATH_MAP[twoSegment]}${rest ? `-${rest}` : ""}`;
  }

  return token.name;
}

export const generateTailwind: GeneratorFn = (tokens) => {
  const lines: string[] = [
    "/* Generated by design-token-pipeline — do not edit */",
    "",
    "@theme {",
  ];

  for (const token of tokens) {
    const name = toTailwindName(token);
    lines.push(`  --${name}: ${token.value};`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
};
