import type { FlatToken, GeneratorFn } from "../types";

function buildNestedObject(
  tokens: FlatToken[],
): Record<string, unknown> {
  const root: Record<string, unknown> = {};

  for (const token of tokens) {
    let current = root;
    for (let i = 0; i < token.path.length - 1; i++) {
      const key = token.path[i];
      if (!(key in current)) current[key] = {};
      current = current[key] as Record<string, unknown>;
    }
    current[token.path[token.path.length - 1]] = token.value;
  }

  return root;
}

function formatValue(value: unknown, indent: number): string {
  const pad = "  ".repeat(indent);
  const innerPad = "  ".repeat(indent + 1);

  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number") return String(value);

  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";

    const lines = entries.map(
      ([key, val]) =>
        `${innerPad}${key}: ${formatValue(val, indent + 1)},`,
    );
    return `{\n${lines.join("\n")}\n${pad}}`;
  }

  return String(value);
}

export const generateTypeScript: GeneratorFn = (tokens) => {
  const nested = buildNestedObject(tokens);
  const formatted = formatValue(nested, 0);

  const lines: string[] = [
    "/* Generated by design-token-pipeline — do not edit */",
    "",
    `export const tokens = ${formatted} as const;`,
    "",
    "export type Tokens = typeof tokens;",
    "",
  ];

  return lines.join("\n");
};
