import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { parse } from "../../src/parser";
import { transform } from "../../src/transformer";
import { generateCSS } from "../../src/generators/css";

const fixture = (name: string) => resolve(__dirname, "..", "fixtures", name);

describe("generateCSS", () => {
  it("generates correct CSS custom properties", () => {
    const tree = parse(fixture("basic-tokens.json"));
    const tokens = transform(tree);
    const output = generateCSS(tokens);

    expect(output).toContain(":root {");
    expect(output).toContain("--color-primary: #0066ff;");
    expect(output).toContain("--color-secondary: #6b7280;");
    expect(output).toContain("--spacing-sm: 8px;");
    expect(output).toContain("--spacing-md: 16px;");
  });

  it("groups tokens by first path segment", () => {
    const tree = parse(fixture("basic-tokens.json"));
    const tokens = transform(tree);
    const output = generateCSS(tokens);

    expect(output).toContain("/* color */");
    expect(output).toContain("/* spacing */");
  });

  it("includes header comment", () => {
    const tokens = transform(parse(fixture("basic-tokens.json")));
    const output = generateCSS(tokens);
    expect(output).toContain("Generated by design-token-pipeline");
  });

  it("matches snapshot for full token set", () => {
    const tokens = transform(parse(fixture("full-tokens.json")));
    const output = generateCSS(tokens);
    expect(output).toMatchSnapshot();
  });
});
